"""AsyncChunkBroker — execute an action chunk while the next one is already being inferred.

:class:`~yam_policy.action_chunk_broker.ActionChunkBroker` is *synchronous*: it hands out one
action per tick and, on the tick the chunk runs out, blocks the control loop for a full policy
round-trip (network + GPU). At 30 Hz with a 30-step chunk that is a stall every second, and the
robot physically stops for the whole inference: the controller has no new target, so it settles
on its last one and holds. That periodic dead-stop is visible in every rollout video.

This broker removes the stall by overlapping inference with execution:

* **Prefetch.** When the chunk in hand has only ``prefetch_ticks`` steps left, the next inference
  is started on a background thread. Execution continues from the current chunk meanwhile, so the
  control loop keeps sending an action every tick and the arm never waits.
* **Delay alignment.** The reply is *not* consumed from index 0. A chunk requested with the
  observation of global step ``N`` predicts actions for steps ``N, N+1, ...``; by the time it
  arrives the robot is at step ``M``, so consumption starts at index ``d = M - N`` -- the actions
  for steps already executed are dropped. ``d`` IS the inference delay in ticks, the same
  quantity RTC calls the inference delay. Without this correction, async prefetch would replay
  stale actions and the arm would judder backwards at every chunk boundary.
* **Underrun fallback.** If the reply has not arrived by the time the chunk is exhausted, the
  control thread blocks on it -- exactly the old synchronous behaviour, and the only case where a
  stall can still happen. Underruns are counted and logged, so a server too slow for the chunk
  duration is visible rather than silently degrading.

**Why this is also the RTC substrate.** Real-Time Chunking (Physical Intelligence,
arXiv:2506.07339) needs three things this class already computes: the inference delay ``d``, the
*unexecuted prefix* of the chunk in hand at request time (:meth:`leftover`), and inference
overlapped with execution. RTC then adds server-side prefix guidance -- the new chunk is
generated by inpainting, constrained to continue that prefix -- which removes the discontinuity at
the splice. Nothing here needs the policy to change: without guidance the splice is a plain jump
(small, since both chunks were predicted from observations one delay apart), and with a
prefix-aware server the same ``leftover()`` is what gets sent. The hook is :meth:`set_prefix_fn`.

Thread model: exactly one inference is ever in flight, and only the background worker calls the
wrapped policy, so a non-thread-safe client (e.g. a websocket connection) is never used
concurrently. The control thread only reads/updates the cursor under a lock, and blocks on an
Event when it underruns. Results from a superseded generation (after :meth:`reset`) are
discarded.
"""

from __future__ import annotations

import logging
import threading
import time
from typing import Callable, Dict, Optional

import numpy as np

from .action_chunk_broker import _slice_step, chunk_len, is_chunked
from .base_policy import BasePolicy

logger = logging.getLogger(__name__)

#: Ticks of headroom added to the measured inference delay when sizing the prefetch trigger.
#: The request has to be issued early enough that the reply lands *before* the chunk runs out;
#: one tick of margin absorbs ordinary jitter, and the estimate itself is an EMA maximum so a
#: single slow inference widens the trigger rather than causing an underrun next chunk.
DEFAULT_MARGIN_TICKS = 2

#: Prefetch trigger used before any inference has been timed.
DEFAULT_PREFETCH_TICKS = 5

#: How long the control thread waits for an underrun reply before giving up. Generous: a slow
#: first inference (model warm-up, JIT) is normal, and the caller treats an exception as a lost
#: policy connection.
WAIT_TIMEOUT_S = 60.0


class LatencyTracker:
    """Inference latency, in seconds and in control ticks.

    Keeps an exponential moving average biased toward the *maximum*: the number is used to decide
    how early to prefetch, and being late costs an underrun (a visible stall) while being early
    only costs a slightly staler chunk. So the estimate rises immediately to any new peak and
    decays slowly.
    """

    def __init__(self, rate_hz: float, alpha: float = 0.2) -> None:
        self.rate_hz = float(max(rate_hz, 1e-6))
        self.alpha = float(alpha)
        self._ema = 0.0
        self.last = 0.0
        self.count = 0

    def observe(self, seconds: float) -> None:
        seconds = float(max(seconds, 0.0))
        self.last = seconds
        self.count += 1
        # Rise instantly, fall slowly (see the class docstring).
        self._ema = seconds if seconds > self._ema else (1 - self.alpha) * self._ema + self.alpha * seconds

    @property
    def estimate_s(self) -> float:
        return self._ema

    @property
    def estimate_ticks(self) -> int:
        return int(np.ceil(self._ema * self.rate_hz))

    @property
    def last_ticks(self) -> int:
        return int(np.ceil(self.last * self.rate_hz))


class AsyncChunkBroker(BasePolicy):
    """One action per :meth:`infer`, with the next chunk fetched in the background.

    Drop-in for :class:`ActionChunkBroker`: same constructor position, same per-step reply (the
    chunk's extras are sliced by the same rule), same :meth:`reset`.
    """

    def __init__(
        self,
        policy: BasePolicy,
        *,
        rate_hz: float = 30.0,
        margin_ticks: int = DEFAULT_MARGIN_TICKS,
        prefetch_ticks: int = 0,
    ) -> None:
        self._policy = policy
        self._latency = LatencyTracker(rate_hz)
        self._margin = int(max(margin_ticks, 0))
        #: Fixed prefetch trigger; 0 means "derive it from the measured latency".
        self._fixed_prefetch = int(max(prefetch_ticks, 0))

        self._lock = threading.Lock()
        self._arrived = threading.Event()

        self._results: Dict | None = None  # chunk in hand
        self._cursor = 0  # next index to consume from it
        self._chunk = 0
        self._chunked = True
        self._step = 0  # global count of actions handed out
        self._chunk_index = -1  # which chunk the current action came from

        self._inflight = False
        self._request_step = 0  # global step whose observation was sent
        self._pending: Dict | None = None  # arrived, not yet spliced in
        self._error: BaseException | None = None
        self._generation = 0

        self._prefix_fn: Optional[Callable[[np.ndarray], Dict]] = None

        # Diagnostics the deploy UI / dataset provenance read.
        self.underruns = 0
        self.stale_chunks = 0
        self._last_delay_ticks = 0
        self._last_infer_s = 0.0

    # ---------------------------------------------------------------- introspection
    @property
    def action_horizon(self) -> int:
        """The chunk size last observed (0 before the first inference)."""
        return self._chunk

    @property
    def chunk_index(self) -> int:
        """How many chunks have been spliced in, minus one (-1 before the first).

        Same name and meaning as on :class:`ActionChunkBroker`, so a caller watching for "a new
        reply arrived, record its length" works against either broker.
        """
        with self._lock:
            return self._chunk_index

    def leftover(self) -> Optional[np.ndarray]:
        """The unexecuted tail of the chunk in hand -- RTC's prefix.

        ``actions[cursor:]``: the actions this broker still intends to execute. At the moment a
        new chunk is requested this is exactly what a prefix-guided (RTC) server would be given to
        inpaint against, and it is what a continuity check should compare the new chunk to. None
        when no chunk is in hand.
        """
        with self._lock:
            if self._results is None or not self._chunked:
                return None
            actions = self._results.get("actions")
            if not isinstance(actions, np.ndarray) or actions.ndim < 2:
                return None
            return np.array(actions[self._cursor :], copy=True)

    def set_prefix_fn(self, fn: Optional[Callable[[np.ndarray], Dict]]) -> None:
        """Install the RTC hook: ``fn(leftover) -> extra observation keys`` sent with the request.

        Left unset, requests carry the plain observation and the server is free of any notion of a
        prefix (today's behaviour). Set it, and a prefix-aware server receives the unexecuted
        actions alongside the observation -- which is all that separates this from real RTC on the
        client side.
        """
        self._prefix_fn = fn

    def stats(self) -> Dict:
        """Timing/provenance of the action just returned, for the UI and the dataset."""
        with self._lock:
            return {
                "chunk_index": self._chunk_index,
                "step_in_chunk": max(self._cursor - 1, 0),
                "chunk_len": self._chunk,
                "infer_ms": self._last_infer_s * 1000.0,
                "delay_ticks": self._last_delay_ticks,
                "prefetch_ticks": self._prefetch_trigger(),
                "underruns": self.underruns,
                "stale_chunks": self.stale_chunks,
                "inflight": self._inflight,
            }

    # ---------------------------------------------------------------- internals
    def _prefetch_trigger(self) -> int:
        """How many steps must remain before the next inference is started."""
        if self._fixed_prefetch:
            return self._fixed_prefetch
        if self._latency.count == 0:
            return DEFAULT_PREFETCH_TICKS
        return max(1, self._latency.estimate_ticks + self._margin)

    def _start_request(self, obs: Dict, generation: int, request_step: int) -> None:
        """Kick off one inference on a background thread (caller holds the lock).

        ``request_step`` is the global step whose OBSERVATION is being sent -- i.e. the tick this
        ``infer`` call is serving, which is ``_step`` before it is incremented. The reply's index 0
        is the action for that step, so the splice depends on getting this exactly right: taking
        the post-increment ``_step`` here would consume every chunk one tick late.
        """
        self._inflight = True
        self._request_step = int(request_step)
        self._arrived.clear()
        payload = dict(obs)
        if self._prefix_fn is not None:
            leftover = None
            if self._results is not None and self._chunked:
                actions = self._results.get("actions")
                if isinstance(actions, np.ndarray) and actions.ndim >= 2:
                    leftover = np.array(actions[self._cursor :], copy=True)
            if leftover is not None and len(leftover):
                try:
                    payload.update(self._prefix_fn(leftover))
                except Exception as e:  # a bad hook must not take the rollout down
                    logger.warning("prefix_fn failed, sending the plain observation: %s", e)
        threading.Thread(
            target=self._worker,
            args=(payload, generation),
            name="chunk-prefetch",
            daemon=True,
        ).start()

    def _worker(self, obs: Dict, generation: int) -> None:
        t0 = time.monotonic()
        try:
            results = self._policy.infer(obs)
            elapsed = time.monotonic() - t0
        except BaseException as e:
            with self._lock:
                if generation == self._generation:
                    self._error = e
                    self._inflight = False
            self._arrived.set()
            return
        with self._lock:
            if generation != self._generation:
                return  # superseded by a reset; drop it
            self._latency.observe(elapsed)
            self._pending = results
            self._last_infer_s = elapsed
            self._inflight = False
        self._arrived.set()

    def _activate_pending(self) -> bool:
        """Splice an arrived chunk in, dropping the steps that have already been executed.

        Caller holds the lock. Returns False when the whole reply is already in the past (the
        inference took longer than the chunk it was predicting), in which case there is nothing
        to execute and a fresh request is needed.
        """
        results = self._pending
        self._pending = None
        if results is None:
            return False
        chunk = chunk_len(results)
        delay = self._step - self._request_step  # RTC's inference delay, in ticks
        self._last_delay_ticks = delay
        if delay >= chunk:
            # The reply predicts only steps we have already executed.
            self.stale_chunks += 1
            logger.warning(
                "policy reply was stale on arrival (delay %d ticks >= chunk %d) — inference is "
                "slower than the chunk it predicts; re-requesting",
                delay,
                chunk,
            )
            return False
        self._results = results
        self._chunk = chunk
        self._chunked = is_chunked(results)
        self._cursor = delay
        self._chunk_index += 1
        return True

    # ---------------------------------------------------------------- BasePolicy
    def infer(self, obs: Dict) -> Dict:
        with self._lock:
            if self._error is not None:
                err, self._error = self._error, None
                raise err
            # The step this call serves. `obs` describes the robot NOW, so any request issued
            # during this call -- underrun or prefetch -- predicts from here (see _start_request).
            obs_step = self._step
            if self._results is None and self._pending is not None:
                self._activate_pending()
            need_blocking_wait = self._results is None
            generation = self._generation
            if need_blocking_wait and not self._inflight:
                self._start_request(obs, generation, obs_step)

        # Underrun (or the very first call): the control loop has nothing to send, so wait for the
        # reply. This is the synchronous behaviour, and the only path that can stall the robot.
        while need_blocking_wait:
            if not self._arrived.wait(WAIT_TIMEOUT_S):
                raise TimeoutError("policy did not answer within %.0fs" % WAIT_TIMEOUT_S)
            with self._lock:
                if self._error is not None:
                    err, self._error = self._error, None
                    raise err
                if self._generation != generation:
                    generation = self._generation  # reset underneath us; re-issue below
                if self._activate_pending():
                    need_blocking_wait = False
                elif not self._inflight:
                    if self._chunk:  # not the first call -> a real underrun, count it
                        self.underruns += 1
                    self._start_request(obs, self._generation, obs_step)
                    generation = self._generation

        with self._lock:
            results = _slice_step(self._results, self._cursor) if self._chunked else self._results
            self._cursor += 1
            self._step += 1
            exhausted = self._cursor >= self._chunk
            remaining = self._chunk - self._cursor
            # Prefetch: start the next inference while there is still chunk left to execute.
            if not self._inflight and self._pending is None and remaining <= self._prefetch_trigger():
                self._start_request(obs, self._generation, obs_step)
            if exhausted:
                self._results = None
                if self._pending is not None:
                    self._activate_pending()
        return results

    def reset(self) -> None:
        """Drop the chunk in hand and any in-flight reply, then reset the wrapped policy.

        Waits out an inference that is already running rather than calling into the wrapped policy
        while the worker is inside it -- a websocket client is not reentrant.
        """
        with self._lock:
            self._generation += 1
            inflight = self._inflight
        if inflight:
            self._arrived.wait(WAIT_TIMEOUT_S)
        with self._lock:
            self._results = None
            self._pending = None
            self._error = None
            self._inflight = False
            self._cursor = 0
            self._chunk = 0
            self._step = 0
            self._chunk_index = -1
            self._last_delay_ticks = 0
            self._arrived.clear()
        self._policy.reset()
