#!/bin/bash
#
# Interactive setup of persistent SocketCAN names for a bimanual YAM setup.
#
# You plug the four candle/candlelight USB-CAN adapters in ONE AT A TIME, in the
# order prompted (leader_l, leader_r, follower_l, follower_r). For each one the
# script detects the newly-enumerated canX interface, reads its serial, and from
# that builds /etc/udev/rules.d/90-can.rules so the names always map to the same
# physical adapter regardless of future plug order.
#
# Names match i2rt/serving/teleop_common.py  (must start with "can", <=13 chars):
#   can_leader_l  can_leader_r  can_follower_l  can_follower_r
#
# Usage:
#   bash robot/setup_can_ids.sh
#
if [ -z "${BASH_VERSION:-}" ]; then
    exec bash "$0" "$@"
fi

set -euo pipefail

if [ "$(id -u)" != "0" ]; then
    SUDO="sudo"
else
    SUDO=""
fi

RULES_FILE="/etc/udev/rules.d/90-can.rules"
BITRATE=1000000

# Order is the order you will plug them in. Edit if you prefer a different order.
ROLES=("can_leader_l" "can_leader_r" "can_follower_l" "can_follower_r")

# List currently-present CAN interfaces (kernel can0.. or already-renamed can_*).
list_can() {
    ls /sys/class/net/ 2>/dev/null | grep -E '^can' || true
}

# Read the adapter's own serial (top-most ATTRS{serial} in the device tree).
# NOTE: no early-exiting filter (e.g. `grep -m1` / `head`) in this pipe -- that
# would SIGPIPE `udevadm` and, under `set -o pipefail`/`set -e`, kill the script.
# `grep` reads all output; `sed` only substitutes on line 1 but still reads to EOF.
serial_of() {
    local iface="$1"
    udevadm info -a -p "/sys/class/net/${iface}" \
        | grep 'ATTRS{serial}==' \
        | sed -nE '1 s/.*ATTRS\{serial\}=="([^"]+)".*/\1/p'
}

echo "=== Persistent CAN ID setup (bimanual) ==="
echo "You will plug in 4 adapters one at a time."
echo
echo "TIP: start with everything UNPLUGGED for a clean mapping."
read -r -p "Press Enter when all four adapters are UNPLUGGED... " _

declare -A SERIALS   # name -> serial

baseline="$(list_can | sort)"
if [ -n "$baseline" ]; then
    echo "WARNING: CAN interfaces are already present:"
    echo "$baseline" | sed 's/^/    /'
    echo "These will be ignored as 'already there'; unplug them for best results."
fi

for name in "${ROLES[@]}"; do
    echo
    echo "------------------------------------------------------------"
    echo ">>> Now plug in the adapter for:  ${name}"
    echo "------------------------------------------------------------"

    before="$(list_can | sort)"

    # Wait (up to ~30s) for exactly one new interface to appear.
    new=""
    for _ in $(seq 1 60); do
        after="$(list_can | sort)"
        new="$(comm -13 <(echo "$before") <(echo "$after") || true)"
        [ -n "$new" ] && break
        sleep 0.5
    done

    count="$(echo "$new" | grep -c . || true)"
    if [ "$count" -eq 0 ]; then
        echo "ERROR: no new CAN interface detected after 30s. Aborting." >&2
        exit 1
    elif [ "$count" -gt 1 ]; then
        echo "ERROR: more than one new interface appeared:" >&2
        echo "$new" | sed 's/^/    /' >&2
        echo "Plug adapters ONE AT A TIME and retry." >&2
        exit 1
    fi

    serial="$(serial_of "$new")"
    if [ -z "$serial" ]; then
        echo "ERROR: could not read serial for $new." >&2
        exit 1
    fi

    SERIALS["$name"]="$serial"
    echo "    detected interface : $new"
    echo "    serial             : $serial"
    echo "    -> will be named   : $name"
done

# --- Write the udev rules ---------------------------------------------------
echo
echo "=== Writing $RULES_FILE ==="
tmp="$(mktemp)"
{
    echo "# Generated by robot/setup_can_ids.sh"
    for name in "${ROLES[@]}"; do
        echo "SUBSYSTEM==\"net\", ACTION==\"add\", ATTRS{serial}==\"${SERIALS[$name]}\", NAME=\"${name}\""
    done
} > "$tmp"

echo "----------------------------------------"
cat "$tmp"
echo "----------------------------------------"
$SUDO cp "$tmp" "$RULES_FILE"
rm -f "$tmp"

# --- Reload + apply ---------------------------------------------------------
echo
echo "=== Reloading udev rules ==="
$SUDO udevadm control --reload-rules
$SUDO udevadm trigger

echo
echo "Replug all four adapters now so the new names take effect."
read -r -p "Press Enter once all four are plugged back in... " _

# --- Bring interfaces up ----------------------------------------------------
echo
echo "=== Bringing interfaces up at ${BITRATE} bit/s ==="
for name in "${ROLES[@]}"; do
    if [ -e "/sys/class/net/${name}" ]; then
        $SUDO ip link set "$name" up type can bitrate "$BITRATE" || \
            echo "    WARN: failed to bring up $name"
        echo "    up: $name"
    else
        echo "    WARN: $name not present yet (replug it, then re-run this section)"
    fi
done

# --- Verify -----------------------------------------------------------------
echo
echo "=== Verify ==="
ip link show | grep -E "can_(leader|follower)_[lr]" || echo "No named CAN interfaces found!"

echo
echo "Done. Sanity-check the arms with, e.g.:"
echo "    python i2rt/motor_config_tool/ping_motors.py --channel can_follower_l"
echo "    python robot/read_encoder.py --channel can_leader_l"
echo
echo "Note: 'ip link ... up' does not persist across reboot. Re-run the bring-up"
echo "loop (or 'bash robot/reset_all_can.sh') after each boot."
